export const SLIDER_DATA_REQUEST = 'SLIDER_DATA_REQUEST';
export const SLIDER_DATA_SUCCESS = 'SLIDER_DATA_SUCCESS';
export const SLIDER_DATA_FAILURE = 'SLIDER_DATA_FAILURE';

export const POPULAR_PRODUCT_DATA_REQUEST = 'POPULAR_PRODUCT_DATA_REQUEST';
export const POPULAR_PRODUCT_DATA_SUCCESS = 'POPULAR_PRODUCT_DATA_SUCCESS';
export const POPULAR_PRODUCT_DATA_FAILURE = 'POPULAR_PRODUCT_DATA_FAILURE';
