// export const URL = 'http://180.149.241.208:3022/';

export const URL = 'https://7af29f57f71c.ngrok.io/';


export const SLIDER_DATA_REQUEST = 'SLIDER_DATA_REQUEST';
export const SLIDER_DATA_SUCCESS = 'SLIDER_DATA_SUCCESS';
export const SLIDER_DATA_FAILURE = 'SLIDER_DATA_FAILURE';

export const POPULAR_PRODUCT_DATA_REQUEST = 'POPULAR_PRODUCT_DATA_REQUEST';
export const POPULAR_PRODUCT_DATA_SUCCESS = 'POPULAR_PRODUCT_DATA_SUCCESS';
export const POPULAR_PRODUCT_DATA_FAILURE = 'POPULAR_PRODUCT_DATA_FAILURE';

export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS';
export const PRODUCT_DATA_FAILURE = 'PRODUCT_DATA_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_AUTHENTICATION = 'LOGIN_AUTHENTICATION';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const CART_DATA_REQUEST = 'CART_DATA_REQUEST';
export const CART_DATA_SUCCESS = 'CART_DATA_SUCCESS';
export const CART_DATA_FAILURE = 'CART_DATA_FAILURE';

export const CART_ITEM_COUNT = 'CART_ITEM_COUNT';

